org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=fox_trot_brew
mod_name=Fox Trot Brew
mod_license=MIT
mod_version=1.0.0-mc1.20.1-forge
mod_group_id=com.chinaex123.fox_trot_brew
mod_authors=ChinaEX123, Fvue233
mod_description=Let the sake fox do the grape-stomping for you — brewing has never been so graceful.